In [9]:
import sys
print (sys.version)
#http://cs231n.github.io/python-numpy-tutorial/

3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]


In [2]:
import numpy as np
a = 1
b = a/2
print(b) #0.5 not 0
a=1.
b=a/2
print(b)
c = [1,2,3,4]

0.5
0.5


In [15]:
a = np.array([1,2,3]) #
print(type(a))
print(a.shape) #row and shape
print(a[0])

<class 'numpy.ndarray'>
(3,)
1


In [22]:
a[0]=5
print(a)
print()
b = np.array( [ [1,2,3],[4,5,6] ] )
print (b)
print (b.shape)

[5 2 3]

[[1 2 3]
 [4 5 6]]
(2, 3)


In [24]:
b[:1,1:]

array([[2, 3]])

In [27]:
c=np.ones((1,2))
print (c)

[[ 1.  1.]]


In [30]:
d = np.random.randn(2,3) #  (N)ormal
print (d)


[[ 0.82133704 -0.30616594 -1.03908207]
 [-0.76403507 -1.57706983  0.81462089]]


In [17]:
e = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print (e,"\n")

f = np.array([0,2,0,1])
print(e[np.arange(4),f],"\n") #indexing

print(np.arange(4),"\n")
e[np.arange(4),f]+=10 #indexing

print(e)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[ 1  6  7 11] 

[0 1 2 3] 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [19]:
e_evenfirstcolumn = e[e[:,0]%2==0]
e_evenfirstcolumn

array([[ 4,  5, 16],
       [10, 21, 12]])

In [29]:
#array math
x = np.array([[1,2],[3,4]],dtype = np.float64)
y = np.array([[5,6],[7,8]],dtype = np.float64)
print (x)
print(y)

print("")
print(x+y)
print(np.add(x,y))
print("")
print(x-y)
print(np.subtract(x,y))
print("")
print(x*y)
print(np.multiply(x,y))
print("")
print(x/y)
print(np.divide(x,y))
print("")
print(np.sqrt(x))

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [36]:
# Matrix Operation
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print (x*y)

[[ 5 12]
 [21 32]]


In [34]:
#broadcasting
print (a)
print(a+1)
print (a)
a+=2
print (a)

[5 2 3]
[6 3 4]
[5 2 3]
[7 4 5]


In [35]:
#matrix operateion
#transpose
print(b)
print(b.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [40]:
# operation by axis
x = np.array([[1,2],[3,4]])
print (x)
print(np.sum(x))
print(np.sum(x,axis = 0)) #by coloum
print(np.sum(x,axis = 1)) #by row


[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [33]:
#dot product
x = np.array([1,2,3])
y = np.array([2,3,4])
print (x*y)
print(np.dot(x,y))


[ 2  6 12]
20
6


In [42]:
x = np.array([[1,2,3],[2,3,4]])
print(x.shape)
y = np.array([[1,2],[2,3],[3,4]])
print(y.shape)
print(np.dot(x,y))
#
#  1,2,3      1,2
#  2,3,4   *  2,3
#             3,4

(2, 3)
(3, 2)
[[14 20]
 [20 29]]
